SUCCESS_STATUS = "SUCCESS"
FAILED_STATUSES = ("FAILURE", "FAILED")
VALID_STATUSES = (SUCCESS_STATUS, *FAILED_STATUSES)
VALID_PAYMENT_MODES = ("UPI", "CARD")

FAILED_STATUS_SQL = "('FAILURE','FAILED')"
VALID_STATUS_SQL = "('SUCCESS','FAILURE','FAILED')"
VALID_PAYMENT_MODE_SQL = "('UPI','CARD')"

